#!/usr/bin/env python3
# -*- coding: utf-8 -*-

print("=== SCROLL PARA TODAS AS TELAS ===")
print()
print("🔧 NOVA ESTRATÉGIA:")
print("  ✅ Scroll individual em cada componente")
print("  ✅ Scroll global que tenta aplicar em todos")
print("  ✅ Bind direto nos widgets")
print()
print("📋 COMPONENTES COM SCROLL:")
print("  • Canvas do formulário")
print("  • Treeview de clientes") 
print("  • Canvas dos cards de pedidos")
print("  • Frame dos pedidos")
print("  • Aplicação inteira (global)")
print()
print("🎯 TESTE AGORA:")
print("  1. Execute a aplicação")
print("  2. Teste o scroll em qualquer lugar")
print("  3. Deve funcionar em todas as abas!")
print()
print("💡 Se ainda não funcionar, o problema pode ser:")
print("   - Driver do mouse")
print("   - Configuração do Windows")
print("   - Conflito com outros programas")
print()
print("✅ Scroll configurado para TODAS as telas!")
